## ❤️ Support Ford Triplog

Ford Triplog is a free and open-source project.

If you enjoy using the integration and would like to support its ongoing development, you can do so with a voluntary donation.

➡️ https://www.paypal.com/paypalme/dompressor

Thank you for your support!
