import_charging_sites:
  fields:
    file:
      required: true
      example: import/charging_sites_ch.json
      selector:
        text:

download_charging_database:
  fields:
    country:
      required: true
      example: CH
      selector:
        text:
